draw_set_font(fnt_test);
draw_set_color(c_white);
str = "You can load things:";
key = ord("1");
test_sprite("Background", spr_background);
test_sprite("Bee", spr_bee);
test_sprite("Thinking, etc.", spr_thinking);
test_group("Default texture group", "Default");
//test_tileset("Tileset", ts_tiles);
draw_text(5, 5, str);